##
## EPITECH PROJECT, 2022
## my_ls
## File description:
## Makefile
##


all:
	@make -C antman -s
	@make -C giantman -s

clean:
	@make -C antman clean -s
	@make -C giantman clean -s

fclean:
	@make -C antman fclean -s
	@make -C giantman fclean -s

re: fclean all
